### ISSUE TITLE
Error: package.json not found

### ISSUE THREAD

**Issue by LoveSpirals** [brunojppb/remix-express-typescript#1]
I'm trying to test the use of local HTTPS with Typescript, and this project seems to give a good example.
I cloned this repo on Windows 10 machine and followed instructions in ReadMe.
After running `npm run dev`, I see:

```
Error: package.json not found
    at PackageJson.load (C:\code\remix-express-typescript\node_modules\@npmcli\package-json\lib\index.js:47:13)
    at async PackageJson.load (C:\code\remix-express-typescript\node_modules\@npmcli\package-json\lib\index.js:33:12)
    at async Object.readConfig (C:\code\remix-express-typescript\node_modules\@remix-run\dev\dist\config.js:174:17)
    at async Object.dev (C:\code\remix-express-typescript\node_modules\@remix-run\dev\dist\cli\commands.js:229:18)
    at async Object.run (C:\code\remix-express-typescript\node_modules\@remix-run\dev\dist\cli\run.js:498:7)
```

Inside `commands.js`, `remixRoot` is being set to `./server/dev.ts`, which explains why the loader can't find `package.json`.
I hard-code `remixRoot` to `undefined`, which causes `'tsx' is not recognized as an internal or external command, ,operable program or batch file.` Next I changed the npm script command to: `"dev": "remix dev -c \"tsx ./server/dev.ts\""`. That sort of works, but give me another error:
```
Express server listening on port 3000
Error: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at u (file:///C:/code/remix-express-typescript/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2406)
    at u (file:///C:/code/remix-express-typescript/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2269)
    at nextResolve (node:internal/modules/esm/loader:163:22)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:24)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
```
It looks like Express is starting, but somewhere an absolute path is being treated as a URL.

Any thoughts on these?
- Why `remixRoot` gets set incorrectly
- Why an absolute path is assumed

Thanks!

**Comment by brunojppb** [comment]
Hey @LoveSpirals I'm mostly using MacOS and Linux. It's probably why I've not hit this issue. I've not tried it myself, but have you tried using WSL to see if that works out?

**Comment by LoveSpirals** [comment]
Hi @brunojppb - Thanks for getting back to me. I didn't figure out this particular problem, but I found [another project](https://github.com/kiliman/remix-ras-server-example) that gets Remix running locally with https using a similar `server.ts`.

**Comment by abenhamdine** [comment]
same error here on Windows : 

```
Error: package.json not found
    at PackageJson.load (D:\GitHub\remix-express-typescript\node_modules\@npmcli\package-json\lib\index.js:47:13)
    at async Function.load (D:\GitHub\remix-express-typescript\node_modules\@npmcli\package-json\lib\index.js:33:12)
    at async Object.readConfig (D:\GitHub\remix-express-typescript\node_modules\@remix-run\dev\dist\config.js:296:17)
    at async Object.dev (D:\GitHub\remix-express-typescript\node_modules\@remix-run\dev\dist\cli\commands.js:227:18)
    at async Object.run (D:\GitHub\remix-express-typescript\node_modules\@remix-run\dev\dist\cli\run.js:515:7)
```
